---
name: "Dev Image Build & Deployment"

on:
  push:
    branches:
      - dev

jobs:

  build:
     runs-on: ubuntu-latest
     env:
       packer_version: "1.9.4"
     steps:
       - name: "Repository Checkout"
         uses: actions/checkout@v3

       - name: "Packer Installation"
         uses: hashicorp/setup-packer@main
         with:
           version: ${{ env.packer_version }}

       - name: "Packer Init"
         run: packer init .
         working-directory: ./packer/

       - name: "Packer Validate"
         run: packer validate -var-file="dev.pkrvars.hcl" .
         working-directory: ./packer/

       - name: "Format Packer Template"
         run: packer fmt .
         working-directory: ./packer/

       - name: "Packer build Image"
         run: packer build -var-file="dev.pkrvars.hcl" .
         working-directory: ./packer/
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.DEV_REGION }}
